import type { StrategyLesson } from "./types";

export const COVERAGE_GUARDRAIL = {
  minWatchableCoveragePct: 8,
  minWatchableSignals: 1,
  weakLongScore: 48, // allow weak bias earlier (aligned with relaxed classifier)
  weakShortScore: 52,
} as const;

export const BASELINE_LESSONS: StrategyLesson[] = [
  {
    setupType: "trend_continuation",
    regime: "TRENDING_UP",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 6,
    minConfidence: 52,
    status: "trusted",
    note: "Long trend continuation — lowered bar to let more real edge through. Final gate is user minConfidence in Strategy Config.",
  },
  {
    setupType: "trend_continuation",
    regime: "TRENDING_DOWN",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 6,
    minConfidence: 52,
    status: "trusted",
    note: "Short trend continuation — lowered bar to let more real edge through. Final gate is user minConfidence in Strategy Config.",
  },
  {
    setupType: "breakout",
    regime: "BREAKOUT",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 4,
    minConfidence: 58,
    status: "trusted",
    note: "Breakouts: lowered from 68. Momentum + volume still preferred but we emit the signal and let confidence + policy decide.",
  },
  {
    setupType: "mean_reversion",
    regime: "VOLATILE",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 3,
    minConfidence: 52,
    status: "watch",
    note: "Volatile regime in crypto often means opportunity. We now emit more of these instead of default HOLD.",
  },
  {
    setupType: "range_trade",
    regime: "RANGING",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -2,
    minConfidence: 55,
    status: "watch",
    note: "Range trades: much lower bar. Structure at extremes can be valid; user controls final minConfidence.",
  },
  {
    setupType: "no_edge",
    regime: "ANY",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -3,
    minConfidence: 50,
    status: "watch",
    note: "Limited edge. Still allow weak directional bias as WEAK_LONG/SHORT so user sees opportunities instead of pure no-trade.",
  },
];
