import type { StrategyLesson } from "./types";

export const COVERAGE_GUARDRAIL = {
  minWatchableCoveragePct: 8,
  minWatchableSignals: 1,
  weakLongScore: 50, // allow weak bias earlier
  weakShortScore: 50,
} as const;

export const BASELINE_LESSONS: StrategyLesson[] = [
  {
    setupType: "trend_continuation",
    regime: "TRENDING_UP",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 5,
    minConfidence: 58,
    status: "trusted",
    note: "Long trend continuation is allowed when trend + at least one confirmation factor align in TRENDING_UP regime.",
  },
  {
    setupType: "trend_continuation",
    regime: "TRENDING_DOWN",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 5,
    minConfidence: 58,
    status: "trusted",
    note: "Short trend continuation is allowed when trend + at least one confirmation factor align in TRENDING_DOWN regime.",
  },
  {
    setupType: "breakout",
    regime: "BREAKOUT",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 3,
    minConfidence: 68,
    status: "trusted",
    note: "Breakouts need above-neutral momentum and volume confirmation before execution.",
  },
  {
    setupType: "mean_reversion",
    regime: "VOLATILE",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -8,
    minConfidence: 72,
    status: "watch",
    note: "Volatile mean reversion is fragile; demand higher confidence until measured results improve.",
  },
  {
    setupType: "range_trade",
    regime: "RANGING",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -4,
    minConfidence: 66,
    status: "watch",
    note: "Range trades are allowed only near structure extremes with limited confidence uplift.",
  },
  {
    setupType: "no_edge",
    regime: "ANY",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -12,
    minConfidence: 62,
    status: "watch",
    note: "Limited edge; only act if other confluence (e.g. multi-TF alignment or strong regime) compensates. Watch-grade only.",
  },
];
