import type { StrategyLesson } from "./types";

export const COVERAGE_GUARDRAIL = {
  minWatchableCoveragePct: 8,
  minWatchableSignals: 1,
  weakLongScore: 52,
  weakShortScore: 48,
} as const;

export const BASELINE_LESSONS: StrategyLesson[] = [
  {
    setupType: "trend_continuation",
    regime: "TRENDING_UP",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 4,
    minConfidence: 64,
    status: "trusted",
    note: "Long trend continuation is allowed when trend, momentum, and volume agree.",
  },
  {
    setupType: "trend_continuation",
    regime: "TRENDING_DOWN",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 4,
    minConfidence: 64,
    status: "trusted",
    note: "Short trend continuation is allowed when trend, momentum, and volume agree.",
  },
  {
    setupType: "breakout",
    regime: "BREAKOUT",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: 3,
    minConfidence: 68,
    status: "trusted",
    note: "Breakouts need above-neutral momentum and volume confirmation before execution.",
  },
  {
    setupType: "mean_reversion",
    regime: "VOLATILE",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -8,
    minConfidence: 72,
    status: "watch",
    note: "Volatile mean reversion is fragile; demand higher confidence until measured results improve.",
  },
  {
    setupType: "range_trade",
    regime: "RANGING",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -4,
    minConfidence: 66,
    status: "watch",
    note: "Range trades are allowed only near structure extremes with limited confidence uplift.",
  },
  {
    setupType: "no_edge",
    regime: "ANY",
    source: "baseline_rule",
    sampleSize: 0,
    winRate: null,
    profitFactor: null,
    confidenceAdjustment: -35,
    minConfidence: 99,
    status: "blocked",
    note: "No-edge signals must stay as HOLD until the setup can be explained and tested.",
  },
];
